eval %sh{
    if [ -d "${kak_runtime}/autoload" ]; then
        find -L "${kak_runtime}/autoload" -type f -name '*\.kak' \
        | sed 's/.*/try %{ source "&" } catch %{ echo -debug Autoload: could not load "&" }/'
    fi
}

def -params 1 -docstring "colorscheme <name>: enable named colorscheme" colorscheme %{source "%val{runtime}/colors/%arg{1}.kak"}
compl -menu colorscheme shell-script-candidates %{
    find -L "${kak_runtime}/colors" -type f -name '*\.kak' | while read -r filename; do
        basename="${filename##*/}"
        printf %s\\n "${basename%.*}"
    done | sort -u
}

source "%val{config}/theme"

require-module clipboard
    map global user p %{:paste-sys-clipboard p<ret>} -docstring 'Past from system clpboard'
    map global user P %{:paste-sys-clipboard P<ret>} -docstring 'Past from system clpboard'
    map global user y :copy-sys-clipboard<ret>       -docstring 'Yank into system Clipboard'
    map global user b :find-edit-buffer<ret>         -docstring 'Serch for the active buffers'

require-module matching
    map global normal <a-'> :surround-selection-on-key<ret>

require-module splits
    map global normal <c-w> ":enter-user-mode window-mode<ret>"

require-module cargo
    map global user c %{:enter-user-mode cargo<ret>}  -docstring "Enter cargo mode" 

add-highlighter global/ number-lines -relative -hlcursor -separator ' '
add-highlighter global/ show-matching

set global startup_info_version 99999999999999
set global ui_options terminal_assistant=cat terminal_synchronized=true
set global tabstop 4
set global scrolloff 5,20
set global autocomplete prompt
set global autoinfo 'command|onkey'
set global autoreload true

require-module langmap
    set global modelinefmt '%val{bufname} %val{cursor_line}:%val{cursor_char_column} 
    {{context_info}} {{mode_info}} - %val{client}@[%val{session}] - (%opt{current_langmap})'

map global insert <c-w> %{<esc>hB<a-c>}
map global insert <c-h> <backspace>
map global insert <c-b> <left>
map global insert <c-f> <right>
map global insert <c-a> %{<a-;>gi}
map global insert <c-e> %{<a-;>gl<a-;>l}
map global insert <a-,> %{<a-;><}
map global insert <a-.> %{<a-;>>}
map global insert <c-d> %{<a-;>;<a-;>"_d}
map global insert <tab> %{<tab><a-;>:exec -draft h@<ret>}

map global normal X x_
map global normal . <a-.>
map global normal <a-.> .
map global normal '#' :comment-line<ret>
map global normal '<a-#>' :comment-block<ret>

# save selections before jumping somewhere:
map global normal / <c-s>/
map global normal ? <c-s>?
map global normal <a-/> <c-s><a-/>
map global normal <a-?> <c-s><a-?>
map global normal * <c-s>*
# move selection (will never use for sure, but looks cool)
map global normal <c-a-k> %{:eval -save-regs \" %{exec dkP}<ret>}
map global normal <c-a-j> %{:eval -save-regs \" %{exec djP}<ret>}
map global normal <c-a-h> %{:eval -save-regs \" %{exec dhP}<ret>}
map global normal <c-a-l> %{:eval -save-regs \" %{exec dlP}<ret>}

map global goto N <esc>:bn<ret>                  -docstring 'Goto next buffer'
map global goto P <esc>:bp<ret>                  -docstring 'Goto previous buffer'
map global goto n <esc>:grep-next-match<ret>     -docstring 'Goto next grep match'
map global goto p <esc>:grep-previous-match<ret> -docstring 'Goto previous grep match'

map global user w :w<ret>                            -docstring 'Save'
map global user . :<ret>                             -docstring 'Repeate last command'
map global user T %{:find-edit-file "../test*"<ret>} -docstring 'Try to fuzzy search for the files in "../tests"'
map global user f %{:find-edit-file .<ret>}          -docstring 'Fuzzy search for the files from current directory'
map global user F %{:find-edit-file ../<ret>}        -docstring 'Fuzzy search for the files from parent directory'

map global insert <c-6> %{<a-;>:switch-langmap ua<ret>}
map global insert <c-7> %{<a-;>:switch-langmap ru<ret>}
map global normal <c-6> %{:switch-langmap ua<ret>}
map global normal <c-7> %{:switch-langmap ru<ret>}

map global normal <c-l> :ls<ret>

map global normal <a-V> :remove-matching-backward<ret>
map global normal <a-v> :remove-matching-forward<ret>

map global normal <a-r> :swap-selections<ret>

map global user  :      :eval-selected-all-sessions<ret> 
map global user ';'     :eval-selected<ret>

# alt + <anyaction> to escape insert mode
evaluate-commands %sh{
    keys='h j k l H J K L 
        o I O A  
        t T f F g G ] [  
        b w e B W E  
        x X 
        c C d 
        m M n N '

    for k in $keys; do
        printf %s "map global insert <a-$k> '<esc>$k' ; "
    done
}

# Cursor color change on entering insert mode 
hook global -group insert-color ModeChange .*:.*:insert %{
    set-face buffer PrimaryCursor InsertCursor
    set-face buffer PrimaryCursorEol InsertCursor
}
hook global -group insert-color ModeChange .*:insert:.* %{ try %{
    unset-face buffer PrimaryCursor 
    unset-face buffer PrimaryCursorEol
} }

# Per filetype settings
hook global BufOpenFile .*\.wgsl %{ set buffer filetype rust }
hook global WinSetOption filetype=(yaml|json|markdown) %{
    rmhooks window markdown-trim-indent 
    set buffer tabstop 2
    set buffer indentwidth 2
}

alias global d delete-buffer

def kill-session -params 1 %{ kill %arg{1} }
compl -menu kill-session shell-script-candidates %{kak -l}

def cdhere %{ cd %sh{ echo $(dirname "$kak_buffile") } }
def eval-selected %{ eval %val{selection} }
def swap-selections %{ try %{ exec '<a-z>a<a-)>' } }
def remove-matching-forward %{exec -save-regs '^"' 'mm;Zm;dzd'}
def remove-matching-backward %{exec -save-regs '^"' '<a-m><a-m>;Zm;dzd'}
def find-edit-buffer %{prompt -menu -buffer-completion 'Buffer: ' %{buffer %val{text}}}
def ls -file-completion %{eval %sh{ printf %s "info -title '$PWD' '$(ls -Alh)'" }}
def lang -params 1 %{ set-option buffer filetype %arg{1} }

def eval-selected-all-sessions %{ eval %sh{
     for s in $(kak -l); do
        echo "$kak_selection" | kak -p "$s"
     done
} }

def find-edit-file -docstring %{
    find-edit-file <path>: list all files in the <path>
} -params 1 %{
    prompt -menu  -shell-script-candidates %exp{
        find -L '%arg[1]' -type f \
            -not -path '*/node_modules/*' \
            -not -path '*/target/*' \
            -not -path '*/.git/*'
    }  'edit ' %{ edit -existing %val{text}  }
}

decl bool auto_save_enabled true
def -hidden write-buffer-if-modified %{ eval -draft %sh{ [ $kak_modified = true ] && printf %s "write" }  }
hook global -group auto-save-manager BufSetOption auto_save_enabled=false %{ rmhooks buffer auto-save }
hook global -group auto-save-manager BufSetOption auto_save_enabled=true %{
    hook -group auto-save buffer ModeChange .*:insert:.* write-buffer-if-modified
    hook -group auto-save buffer NormalKey (q|d|<a-d>|c|<a-c>|r|R|p|P|u|U|<lt>|<a-lt>|<gt>|<a-gt>|!|:|\|`|~) write-buffer-if-modified
}
