def -override -params 1 -docstring %{
    fifo <command>:  run command in a fifo buffer
} fifo %{ eval -save-regs 1 %{
    reg 1 %arg[1]
    eval %sh{
        let cmd = $env.kak_reg_1 
        let output = mktemp --dry -t kak-fifo.XXXXXX
        mkfifo $output
        sh -c $"\( nu -c '($cmd)' > ($output) 2>&1 & ) > /dev/null 2>&1 < /dev/null"
        $output

        $"
            edit! -readonly -fifo ($output) -scroll *fifo* ;
            hook -always -once buffer BufCloseFifo .* %{ nop %sh{ rm ($output) } } ;
        "
    }
} }

decl -hidden str find_edit_path
def find-edit-file -params 1 -docstring 'Will list all files in specified directory' %{ eval -save-regs a %{
    set current find_edit_path %arg[1]
    prompt -menu -shell-script-candidates %{
        (^find $env.kak_opt_find_edit_path
            -type f 
            -not -path '*/node_modules/*' 
            -not -path '*/colors/*' 
            -not -path '*/target/*')
    } 'edit ' %{
        edit -existing %val{text}
    }
} } 

def apply-syntax-hl %{ set buffer filetype %sh{
    [
        { pat: '(kakrc|.*\.kak)' filetype: kak }
        { pat: '.*\.nu' filetype: nu }
    ]
    | where $env.kak_bufname =~ $it.pat
    | get filetype
    | first
} }

def ls %{ info %sh{ ls -a | sort-by { $in.type } } }

def -docstring 'Set filetype for the current buffer' -params 1 lang %{ set buffer filetype %arg[1] }

def -docstring 'Set named theme from "colors" directory' -params 1 -shell-script-candidates %{
    [ $env.kak_runtime colors ]
    | path join
    | ls $in
    | get name
    | path parse
    | get stem
    | str join (char newline)
} theme %{
    source "%val{runtime}/colors/%arg{1}.kak"
}

decl -docstring 'Characters inserted at the beginning of a commented line' str comment_line '#'

def comment-line %{ eval -save-regs '/' -draft %{
    # select lines
    exec <a-s>gi<a-l>
    # keep non-empty
    try %{ exec <a-K>\A\s*\z<ret> }
    set-register / "\A\Q%opt{comment_line}\E\h?"
    try %{ # comment
        exec "<a-K><ret>i%opt{comment_line} "
    } catch %{ # uncomment
        exec s<ret>d
    }
} }

def copy-sys-clipboard  %{ eval %sh{
    wl-copy -- $env.kak_selection e> /dev/null
    'echo -markup {Information}Yanked selection to system clipboard;'
} }

def paste-sys-clipboard -params 1 %{ eval -save-regs dquote %{
    set-register dquote %sh{(wl-paste) e> /dev/null}
    execute-keys %arg{1}
} } 

def enable-syntax-hl %{ hook global -group auto-apply-syntax-hl BufCreate .* %{ apply-syntax-hl } }

def disable-syntax-hl %{ rmhooks global auto-apply-syntax-hl }

decl -hidden bool auto_save_enabled true
hook global -group auto-save-manager BufSetOption auto_save_enabled=true %{
    hook -group auto-save buffer ModeChange .*:insert:.* %{ w }
    hook -group auto-save buffer NormalKey .* %{ eval %sh{
        if ($env.kak_modified | into bool) { 'write' }
    } }
}
hook global -group auto-save-manager BufSetOption auto_save_enabled=false %{
    rmhooks buffer auto-save
}

hook global -group insert-color ModeChange .*:.*:insert %{
    set-face buffer PrimaryCursor InsertCursor
    set-face buffer PrimaryCursorEol InsertCursor
}
hook global -group insert-color ModeChange .*:insert:.* %{ try %{
    unset-face buffer PrimaryCursor
    unset-face buffer PrimaryCursorEol
} }

hook global WinSetOption filetype=(yaml|json|markdown) %{
    rmhooks window markdown-trim-indent 
    set buffer tabstop 2
    set buffer indentwidth 2
}
hook global BufOpenFile .*\.wgsl %{
    set buffer filetype rust
}
hook global BufSetOption filetype=git.* %{
    set buffer auto_save_enabled false
}

alias global d delete-buffer

add-highlighter global/ number-lines -relative -hlcursor -separator ' '
add-highlighter global/ show-matching

set global ui_options terminal_assistant=cat terminal_synchronized=true
set global tabstop 4
set global scrolloff 5,20
set global autocomplete prompt
set global autoinfo 'command|onkey'
set global autoreload true

map global normal '#'   :comment-line<ret>
map global normal <c-l> :ls<ret>

map -docstring 'List files to edit in ./**/*'               global user f   %{:find-edit-file ./<ret>}
map -docstring 'List files to edit in ../**/*'              global user F   %{:find-edit-file ../<ret>}
map -docstring 'Yank into system Clipboard'                 global user y   %{:copy-sys-clipboard<ret>}
map -docstring 'Past from system clpboard after selection'  global user p   %{\\:paste-sys-clipboard p<ret>}
map -docstring 'Past from system clpboard before selection' global user P   %{\\:paste-sys-clipboard P<ret>}
map -docstring 'Save document'                              global user w   %{:w<ret>}
map -docstring 'Evaluate main selection'                    global user ';' %{:eval %val{selection}<ret>}

map global insert <tab> %{<tab><a-;>:exec -draft h@<ret>}

# readline bindings
map global insert <c-w> %{<a-;>b<a-;>"_d}
map global insert <c-h> <backspace>
map global insert <c-b> <left>
map global insert <c-f> <right>
map global insert <c-a> %{<a-;>gi}
map global insert <c-e> %{<a-;>gl<a-;>l}
map global insert <a-,> %{<a-;><}
map global insert <a-.> %{<a-;>>}
map global insert <c-d> %{<a-;>;<a-;>"_d}

map global normal X     x_
map global normal .     <a-.>
map global normal <a-.> .

# save selections before jumping somewhere:
map global normal /     <c-s>/
map global normal ?     <c-s>?
map global normal <a-/> <c-s><a-/>
map global normal <a-?> <c-s><a-?>
map global normal *     <c-s>*

map -docstring 'Goto next buffer'         global goto N <esc>:bn<ret>
map -docstring 'Goto previous buffer'     global goto P <esc>:bp<ret>
map -docstring 'Goto next grep match'     global goto n <esc>:grep-next-match<ret>
map -docstring 'Goto previous grep match' global goto p <esc>:grep-previous-match<ret>

map -docstring 'Save'                     global user w :w<ret>
map -docstring 'Repeate last command'     global user . :<ret>
map -docstring 'Edit buffer'              global user b %{:buffer }

map -docstring 'Move selection up'    global normal <c-a-k> %{:eval -save-regs dquote %{exec dkP}<ret>}
map -docstring 'Move selection down'  global normal <c-a-j> %{:eval -save-regs dquote %{exec djP}<ret>}
map -docstring 'Move selection left'  global normal <c-a-h> %{:eval -save-regs dquote %{exec dhP}<ret>}
map -docstring 'Move selection right' global normal <c-a-l> %{:eval -save-regs dquote %{exec dlP}<ret>}

# alt + <anyaction> to escape insert mode
eval %sh{
    [
        h j k l H J K L
        o I O A
        t T f F g G ']' '['
        b w e B W E
        x X
        c C d
        m M n N
    ] 
    | each { |key| $'map global insert <a-($key)> %{<esc>($key)} ; ' } 
    | str join
    | print

    # source syntax definitions
    [ $env.kak_runtime syntax ]
    | path join
    | ls $in
    | get name
    | each { print $"source '($in)' ; " }
    | str join
    | print
}

enable-syntax-hl
source "%val{runtime}/theme"
source "%val{runtime}/splits.kak"

